package_assets: on
embed_assets: on
gzip_assets: on

javascripts:
  production:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery.timers.1.2.js
    - public/javascripts/application.js
    - public/javascripts/rails.js
    - public/javascripts/jquery.jplayer.min.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/style.css
  mobile:
    - public/stylesheets/reset.css
    - public/stylesheets/style.css
