package_assets: on
embed_assets: on
gzip_assets: on

javascripts:
  production:
    - public/javascripts/jquery.min.js
    - public/javascripts/trainlines.js
    - public/javascripts/jquerydefaultvalue.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/style.css
  mobile:
    - public/stylesheets/reset.css
    - public/stylesheets/style.css
